version: '2'

services:

  scpsl:
    container_name: scpsl
    build: ./scpsl
    mem_limit: 1G
    memswap_limit: 4G
    restart: on-failure
    ports:
      - "7777-7784:7777-7784/udp"
      - "7777-7784:7777-7784"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/scpsl/steamcmd:/home/steam/steamcmd
      - ${MOUNT_POINT}/scpsl/scp_server:/home/steam/scp_server

  creative:
    container_name: creative
    image: nagency/papermc
    mem_limit: 1G
    memswap_limit: 4G
    restart: on-failure
    ports:
      - "25566:25565"
    volumes:
      - ${MOUNT_POINT}/minecraft/creative:/paper/server

  survival:
    container_name: survival
    image: nagency/papermc
    mem_limit: 1G
    memswap_limit: 4G
    restart: on-failure
    ports:
      - "25567:25565"
    volumes:
      - ${MOUNT_POINT}/minecraft/survival:/paper/server

  waterfall:
    container_name: waterfall
    image: nagency/waterfall
    mem_limit: 1G
    memswap_limit: 4G
    restart: on-failure
    ports:
      - "25565:25577"
    volumes:
      - ${MOUNT_POINT}/minecraft/waterfall:/waterfall/proxy
